POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "guest2",
  "password": "123456",
  "confirmPassword": "123456",
  "email": "email2@gmail.com",
  "fullName": "guest2",
  "phone": "095357392"
}