spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BubuShop;encrypt=true;trustServerCertificate=true
spring.datasource.username=bubu_app
spring.datasource.password=Bubu@12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
server.servlet.session.timeout=12h
server.servlet.session.cookie.same-site=lax
spring.web.error.include-message=always